apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greetings
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: greetings
  project: default
  source:
    repoURL: 'git@github.com:YlianaOtero/prueba-cenco.git'
    path: kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
