apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
  namespace: greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: greetings
          image: ylianaotero/prueba-cenco:b51b2e933578661253925f2a54e1daf9a5b9e3bd
          ports:
            - containerPort: 5000