apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
  namespace: greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: greetings
          image: ylianaotero/prueba-cenco:2023-10-07--03-27
          ports:
            - containerPort: 5000