apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
  namespace: greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: greetings
          image: ylianaotero/prueba-cenco:15928438f9bf5a3b373e37780ceadfe61c7b9120
          ports:
            - containerPort: 5000
