apiVersion: v1
kind: Service
metadata:
  name: greetings-service
  namespace: greetings
spec:
  selector:
    app: greetings
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
